language: java
jdk:
- oraclejdk7
- openjdk7
notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: |-
        g6Gpj2n1Bl6hIwWlywEkw8wRjpN2XuFsxFr9KQu/p7mRLYPdF3V5qQPVLBRd
        KvkjCIM7gZy2DTRNUooQPXdJB3npbnlbQn4jNWqA7/fp434Sw5sdfSUMawGr
        XvemLvn0KxQxCO9GfN3wfmYxEWJwXO36Q29BnRWWgMQOXpFFD8A=
after_success:
  - mkdir assemblies
  - mvn -DskipTests package
  - pushd graylog2-server ; mvn assembly:single; popd
  - pushd graylog2-radio ; mvn assembly:single; popd
  - mv graylog2-server/target/assembly/* assemblies/
deploy:
  provider: s3
  access_key_id: AKIAIGYGO43W76PZMMVA
  secret_access_key:
    secure: cYHsMgnAI08sz9G1Qb7ku2HoTaSn/OBBmjBzyYswX0/Kvb2asQcEGZGOEfYNTGOwdN6DP7p3axi5o+FPw2MLGGpBVz3tAtwYWTbzJR8kCEuGwb8N6abpdkGIn4AfifQ+vbn8zJrIB6HfGGRpDM9QnEjJFtpJO+2SjODzbZzkymE=
  bucket: graylog2-builds
  region: eu-west-1
  skip_cleanup: true
  local-dir: assemblies
  on:
    repo: Graylog2/graylog2-server
    jdk: oraclejdk7
