development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: graylog2_development
  pool: 5
  username: graylog2_dev
  password: X3OEDWqBE3lp
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: graylog2_test
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: graylog2_production
  pool: 5
  username: root
  password: 
  socket: /var/run/mysqld/mysqld.sock
